#ifndef BOARDS_H
#define BOARDS_H
#define BOARD_UNKNOWN -1
#define BOARD_GEN7_CUSTOM       10   
#define BOARD_GEN7_12           11   
#define BOARD_GEN7_13           12   
#define BOARD_GEN7_14           13   
#define BOARD_CNCONTROLS_11     111  
#define BOARD_CNCONTROLS_12     112  
#define BOARD_CHEAPTRONIC       2    
#define BOARD_CHEAPTRONIC_V2    21   
#define BOARD_SETHI             20   
#define BOARD_MIGHTYBOARD_REVE  200  
#define BOARD_RAMPS_OLD         3    
#define BOARD_RAMPS_13_EFB      33   
#define BOARD_RAMPS_13_EEB      34   
#define BOARD_RAMPS_13_EFF      35   
#define BOARD_RAMPS_13_EEF      36   
#define BOARD_RAMPS_13_SF       38   
#define BOARD_FELIX2            37   
#define BOARD_RIGIDBOARD        42   
#define BOARD_RIGIDBOARD_V2     52   
#define BOARD_RAMPS_14_EFB      43   
#define BOARD_RAMPS_14_EEB      44   
#define BOARD_RAMPS_14_EFF      45   
#define BOARD_RAMPS_14_EEF      46   
#define BOARD_RAMPS_14_SF       48   
#define BOARD_GEN6              5    
#define BOARD_GEN6_DELUXE       51   
#define BOARD_SANGUINOLOLU_11   6    
#define BOARD_SANGUINOLOLU_12   62   
#define BOARD_MELZI             63   
#define BOARD_STB_11            64   
#define BOARD_AZTEEG_X1         65   
#define BOARD_MELZI_MAKR3D      66   
#define BOARD_AZTEEG_X3         67   
#define BOARD_AZTEEG_X3_PRO     68   
#define BOARD_ANET_10           69   
#define BOARD_ULTIMAKER         7    
#define BOARD_ULTIMAKER_OLD     71   
#define BOARD_ULTIMAIN_2        72   
#define BOARD_3DRAG             77   
#define BOARD_K8200             78   
#define BOARD_K8400             79   
#define BOARD_TEENSYLU          8    
#define BOARD_RUMBA             80   
#define BOARD_PRINTRBOARD       81   
#define BOARD_PRINTRBOARD_REVF  811  
#define BOARD_BRAINWAVE         82   
#define BOARD_SAV_MKI           83   
#define BOARD_TEENSY2           84   
#define BOARD_BRAINWAVE_PRO     85   
#define BOARD_GEN3_PLUS         9    
#define BOARD_GEN3_MONOLITHIC   22   
#define BOARD_MEGATRONICS       70   
#define BOARD_MEGATRONICS_2     701  
#define BOARD_MINITRONICS       702  
#define BOARD_MEGATRONICS_3     703  
#define BOARD_MEGATRONICS_31    704  
#define BOARD_OMCA_A            90   
#define BOARD_OMCA              91   
#define BOARD_RAMBO             301  
#define BOARD_MINIRAMBO         302  
#define BOARD_SCOOVO_X9H        303  
#define BOARD_MEGACONTROLLER    310  
#define BOARD_ELEFU_3           21   
#define BOARD_5DPRINT           88   
#define BOARD_LEAPFROG          999  
#define BOARD_MKS_BASE          40   
#define BOARD_MKS_13            47   
#define BOARD_SAINSMART_2IN1    49   
#define BOARD_BAM_DICE          401  
#define BOARD_BAM_DICE_DUE      402  
#define BOARD_BQ_ZUM_MEGA_3D    503  
#define BOARD_ZRIB_V20          504  
#define	BOARD_ONEPLUS_wanhao	510
#define	BOARD_ONEPLUS1_wanhao	511
#define	BOARD_MELZI_wanhao		520
#define	BOARD_ULTIMAKER_wanhao	530
#define	BOARD_I3PLUS			540
#define	BOARD_F6				541
#define BOARD_I3PLUS3030        542
#define MB(board) (MOTHERBOARD==BOARD_##board)
#endif 
