#ifndef LANGUAGE_ZH_CN_H
#define LANGUAGE_ZH_CN_H
#define WELCOME_MSG                         MACHINE_NAME _UxGT("已就绪.")  
#define MSG_SD_INSERTED                     _UxGT("存储卡已插入")  
#define MSG_SD_REMOVED                      _UxGT("存储卡被拔出")  
#define MSG_LCD_ENDSTOPS                    _UxGT("挡块")  
#define MSG_MAIN                            _UxGT("主菜单")  
#define MSG_AUTOSTART                       _UxGT("自动开始")  
#define MSG_DISABLE_STEPPERS                _UxGT("关闭步进电机")  
#define MSG_AUTO_HOME                       _UxGT("回原点")  
#define MSG_AUTO_HOME_X                     _UxGT("回X原位")  
#define MSG_AUTO_HOME_Y                     _UxGT("回Y原位")  
#define MSG_AUTO_HOME_Z                     _UxGT("回Z原位")  
#define MSG_LEVEL_BED_HOMING                _UxGT("平台调平XYZ归原位")  
#define MSG_LEVEL_BED_WAITING               _UxGT("单击开始热床调平")  
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("下个热床调平点")  
#define MSG_LEVEL_BED_DONE                  _UxGT("完成热床调平")  
#define MSG_SET_HOME_OFFSETS                _UxGT("设置原点偏移")  
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("偏移已启用")  
#define MSG_SET_ORIGIN                      _UxGT("设置原点")  
#define MSG_PREHEAT_1                       _UxGT("预热PLA")  
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")  
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" 全部")  
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" 热床")  
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" 设置")  
#define MSG_PREHEAT_2                       _UxGT("预热ABS")  
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")  
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" 全部")  
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" 热床")  
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" 设置")  
#define MSG_COOLDOWN                        _UxGT("降温")  
#define MSG_SWITCH_PS_ON                    _UxGT("电源打开")  
#define MSG_SWITCH_PS_OFF                   _UxGT("电源关闭")  
#define MSG_EXTRUDE                         _UxGT("挤出")  
#define MSG_RETRACT                         _UxGT("回抽")  
#define MSG_MOVE_AXIS                       _UxGT("移动轴")  
#define MSG_BED_LEVELING                    _UxGT("调平热床")  
#define MSG_LEVEL_BED                       _UxGT("调平热床")  
#define MSG_MOVE_X                          _UxGT("移动X")  
#define MSG_MOVE_Y                          _UxGT("移动Y")  
#define MSG_MOVE_Z                          _UxGT("移动Z")  
#define MSG_MOVE_E                          _UxGT("挤出机")  
#define MSG_MOVE_01MM                       _UxGT("移动 0.1 mm")  
#define MSG_MOVE_1MM                        _UxGT("移动 1 mm")  
#define MSG_MOVE_10MM                       _UxGT("移动 10 mm")  
#define MSG_SPEED                           _UxGT("速率")  
#define MSG_BED_Z                           _UxGT("热床Z")  
#define MSG_NOZZLE                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 喷嘴")  
#define MSG_BED                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 热床")  
#define MSG_FAN_SPEED                       _UxGT("风扇速率")  
#define MSG_FLOW                            _UxGT("挤出速率")  
#define MSG_CONTROL                         _UxGT("控制")  
#define MSG_MIN                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 最小") 
#define MSG_MAX                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 最大")  
#define MSG_FACTOR                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 因数")  
#define MSG_AUTOTEMP                        _UxGT("自动控温")  
#define MSG_ON                              _UxGT("开 ")  
#define MSG_OFF                             _UxGT("关 ")  
#define MSG_PID_P                           _UxGT("PID-P")  
#define MSG_PID_I                           _UxGT("PID-I")  
#define MSG_PID_D                           _UxGT("PID-D")  
#define MSG_PID_C                           _UxGT("PID-C")  
#define MSG_SELECT                          _UxGT("选择")  
#define MSG_ACC                             _UxGT("加速度")  
#define MSG_JERK                            _UxGT("抖动速率")  
#define MSG_VX_JERK                         _UxGT("X轴抖动速率")  
#define MSG_VY_JERK                         _UxGT("Y轴抖动速率")  
#define MSG_VZ_JERK                         _UxGT("Z轴抖动速率")  
#define MSG_VE_JERK                         _UxGT("挤出机抖动速率")  
#define MSG_VMAX                            _UxGT("最大进料速率")  
#define MSG_VMIN                            _UxGT("最小进料速率")  
#define MSG_VTRAV_MIN                       _UxGT("最小移动速率")  
#define MSG_AMAX                            _UxGT("最大打印加速度")  
#define MSG_A_RETRACT                       _UxGT("收进加速度")  
#define MSG_A_TRAVEL                        _UxGT("非打印移动加速度")  
#define MSG_STEPS_PER_MM                    _UxGT("轴步数/mm")  
#define MSG_XSTEPS                          _UxGT("X轴步数/mm")  
#define MSG_YSTEPS                          _UxGT("Y轴步数/mm")  
#define MSG_ZSTEPS                          _UxGT("Z轴步数/mm")  
#define MSG_ESTEPS                          _UxGT("挤出机步数/mm")  
#define MSG_TEMPERATURE                     _UxGT("温度")  
#define MSG_MOTION                          _UxGT("运动")  
#define MSG_FILAMENT                        _UxGT("丝料测容")  
#define MSG_VOLUMETRIC_ENABLED              _UxGT("测容积mm³")  
#define MSG_FILAMENT_DIAM                   _UxGT("丝料直径")  
#define MSG_CONTRAST                        _UxGT("LCD对比度")  
#define MSG_STORE_EEPROM                    _UxGT("保存设置")  
#define MSG_LOAD_EEPROM                     _UxGT("装载设置")  
#define MSG_RESTORE_FAILSAFE                _UxGT("恢复安全值")  
#define MSG_REFRESH                         _UxGT("刷新")  
#define MSG_WATCH                           _UxGT("信息屏")  
#define MSG_PREPARE                         _UxGT("准备")  
#define MSG_TUNE                            _UxGT("调整")  
#define MSG_PAUSE_PRINT                     _UxGT("暂停打印")  
#define MSG_RESUME_PRINT                    _UxGT("恢复打印")  
#define MSG_STOP_PRINT                      _UxGT("停止打印")  
#define MSG_CARD_MENU                       _UxGT("从存储卡上打印")  
#define MSG_NO_CARD                         _UxGT("无存储卡")  
#define MSG_DWELL                           _UxGT("休眠中 ...")  
#define MSG_USERWAIT                        _UxGT("等待用户 ...")  
#define MSG_RESUMING                        _UxGT("恢复打印中")  
#define MSG_PRINT_ABORTED                   _UxGT("打印已取消")  
#define MSG_NO_MOVE                         _UxGT("无移动")  
#define MSG_KILLED                          _UxGT("已杀掉")  
#define MSG_STOPPED                         _UxGT("已停止")  
#define MSG_CONTROL_RETRACT                 _UxGT("回抽长度mm")  
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("换手回抽长度mm")  
#define MSG_CONTROL_RETRACTF                _UxGT("回抽速率mm/s")  
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("Hop mm")  
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("回抽恢复长度mm")  
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("换手回抽恢复长度mm")  
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("回抽恢复后进料速率mm/s")  
#define MSG_AUTORETRACT                     _UxGT("自动抽回")  
#define MSG_FILAMENTCHANGE                  _UxGT("更换丝料")  
#define MSG_INIT_SDCARD                     _UxGT("初始化存储卡")  
#define MSG_CNG_SDCARD                      _UxGT("更换存储卡")  
#define MSG_ZPROBE_OUT                      _UxGT("Z探针在热床之外")  
#define MSG_HOME                            _UxGT("归位")  
#define MSG_FIRST                           _UxGT("先")  
#define MSG_ZPROBE_ZOFFSET                  _UxGT("Z偏移")  
#define MSG_BABYSTEP_X                      _UxGT("微量调整X轴")  
#define MSG_BABYSTEP_Y                      _UxGT("微量调整Y轴")  
#define MSG_BABYSTEP_Z                      _UxGT("微量调整Z轴")  
#define MSG_ENDSTOP_ABORT                   _UxGT("挡块终止")  
#define MSG_HEATING_FAILED_LCD              _UxGT("加热失败")  
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("错误：REDUNDANT TEMP")  
#define MSG_THERMAL_RUNAWAY                 _UxGT("温控失控")  
#define MSG_ERR_MAXTEMP                     _UxGT("错误：最高温度")  
#define MSG_ERR_MINTEMP                     _UxGT("错误：最低温度")  
#define MSG_ERR_MAXTEMP_BED                 _UxGT("错误：最高热床温度")  
#define MSG_ERR_MINTEMP_BED                 _UxGT("错误：最低热床温度")  
#define MSG_HALTED                          _UxGT("打印停机")  
#define MSG_PLEASE_RESET                    _UxGT("请重置")  
#define MSG_SHORT_DAY                       _UxGT("天")  
#define MSG_SHORT_HOUR                      _UxGT("时")  
#define MSG_SHORT_MINUTE                    _UxGT("分")  
#define MSG_HEATING                         _UxGT("加热中 ...")  
#define MSG_HEATING_COMPLETE                _UxGT("完成加热")  
#define MSG_BED_HEATING                     _UxGT("加热热床中")  
#define MSG_BED_DONE                        _UxGT("完成加热热床")  
#define MSG_DELTA_CALIBRATE                 _UxGT("⊿校准")  
#define MSG_DELTA_CALIBRATE_X               _UxGT("校准X")  
#define MSG_DELTA_CALIBRATE_Y               _UxGT("校准Y")  
#define MSG_DELTA_CALIBRATE_Z               _UxGT("校准Z")  
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("校准中心")  
#define MSG_INFO_MENU                       _UxGT("关于打印机")  
#define MSG_INFO_PRINTER_MENU               _UxGT("打印机信息")  
#define MSG_INFO_STATS_MENU                 _UxGT("打印机统计")  
#define MSG_INFO_BOARD_MENU                 _UxGT("主板信息")  
#define MSG_INFO_THERMISTOR_MENU            _UxGT("温度计")  
#define MSG_INFO_EXTRUDERS                  _UxGT("挤出机")  
#define MSG_INFO_BAUDRATE                   _UxGT("波特率")  
#define MSG_INFO_PROTOCOL                   _UxGT("协议")  
#if LCD_WIDTH > 19
#define MSG_INFO_PRINT_COUNT              _UxGT("打印计数")  
#define MSG_INFO_COMPLETED_PRINTS         _UxGT("完成了")  
#define MSG_INFO_PRINT_TIME               _UxGT("总打印时间")  
#define MSG_INFO_PRINT_LONGEST            _UxGT("最长工作时间")  
#define MSG_INFO_PRINT_FILAMENT           _UxGT("总计挤出")  
#else
#define MSG_INFO_PRINT_COUNT              _UxGT("打印数")  
#define MSG_INFO_COMPLETED_PRINTS         _UxGT("完成")  
#define MSG_INFO_PRINT_TIME               _UxGT("总共")  
#define MSG_INFO_PRINT_LONGEST            _UxGT("最长")  
#define MSG_INFO_PRINT_FILAMENT           _UxGT("已挤出")  
#endif
#define MSG_INFO_MIN_TEMP                   _UxGT("最低温度")  
#define MSG_INFO_MAX_TEMP                   _UxGT("最高温度")  
#define MSG_INFO_PSU                        _UxGT("电源供应")  
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("PRINT PAUSED")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("RESUME OPTIONS:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("挤出更多")  
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("恢复打印")  
#if LCD_HEIGHT >= 4
#define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("等待开始")  
#define MSG_FILAMENT_CHANGE_INIT_2          _UxGT("丝料")  
#define MSG_FILAMENT_CHANGE_INIT_3          _UxGT("变更")  
#define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("等待")  
#define MSG_FILAMENT_CHANGE_UNLOAD_2        _UxGT("卸下丝料")  
#define MSG_FILAMENT_CHANGE_UNLOAD_3        _UxGT("")  
#define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("插入丝料")  
#define MSG_FILAMENT_CHANGE_INSERT_2        _UxGT("并按键")  
#define MSG_FILAMENT_CHANGE_INSERT_3        _UxGT("来继续 ...")  
#define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("等待")  
#define MSG_FILAMENT_CHANGE_LOAD_2          _UxGT("进料")  
#define MSG_FILAMENT_CHANGE_LOAD_3          _UxGT("")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("等待")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_2       _UxGT("丝料挤出")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_3       _UxGT("")  
#define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("等待打印")  
#define MSG_FILAMENT_CHANGE_RESUME_2        _UxGT("恢复")  
#define MSG_FILAMENT_CHANGE_RESUME_3        _UxGT("")  
#else 
#define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("请等待 ...")  
#define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("退出中 ...")  
#define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("插入并单击")  
#define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("装载中 ...")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("挤出中 ...")  
#define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("恢复中 ...")  
#endif 
#endif 
