#ifndef LANGUAGE_KANA_UTF_H
#define LANGUAGE_KANA_UTF_H
#define MAPPER_E382E383
#define DISPLAY_CHARSET_ISO10646_KANA
#define WELCOME_MSG                         MACHINE_NAME _UxGT(" ready.")
#define MSG_SD_INSERTED                     _UxGT("カードガソウニュウサレマシタ")        
#define MSG_SD_REMOVED                      _UxGT("カードガアリマセン")               
#define MSG_LCD_ENDSTOPS                    _UxGT("エンドストップ")                  
#define MSG_MAIN                            _UxGT("メイン")                       
#define MSG_AUTOSTART                       _UxGT("ジドウカイシ")                   
#define MSG_DISABLE_STEPPERS                _UxGT("モーターデンゲン オフ")            
#define MSG_DEBUG_MENU                      _UxGT("デバッグメニュー")                
#define MSG_PROGRESS_BAR_TEST               _UxGT("プログレスバー テスト")            
#define MSG_AUTO_HOME                       _UxGT("ゲンテンフッキ")                  
#define MSG_AUTO_HOME_X                     _UxGT("Xジク ゲンテンフッキ")             
#define MSG_AUTO_HOME_Y                     _UxGT("Yジク ゲンテンフッキ")             
#define MSG_AUTO_HOME_Z                     _UxGT("Zジク ゲンテンフッキ")             
#define MSG_LEVEL_BED_HOMING                _UxGT("ゲンテンフッキチュウ")              
#define MSG_LEVEL_BED_WAITING               _UxGT("レベリングカイシ")                
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("ツギノソクテイテンヘ")             
#define MSG_LEVEL_BED_DONE                  _UxGT("レベリングカンリョウ")              
#define MSG_SET_HOME_OFFSETS                _UxGT("キジュンオフセットセッテイ")         
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("オフセットガテキヨウサレマシタ")       
#define MSG_SET_ORIGIN                      _UxGT("キジュンセット")                 
#define MSG_PREHEAT_1                       _UxGT("PLA ヨネツ")                   
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")
#define MSG_PREHEAT_1_ALL                   _UxGT("PLA スベテヨネツ")              
#define MSG_PREHEAT_1_BEDONLY               _UxGT("PLA ベッドヨネツ")              
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT("セッテイ")       
#define MSG_PREHEAT_2                       _UxGT("ABS ヨネツ")                  
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")
#define MSG_PREHEAT_2_ALL                   _UxGT("ABS スベテヨネツ")              
#define MSG_PREHEAT_2_BEDONLY               _UxGT("ABS ベッドヨネツ")              
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT("セッテイ")       
#define MSG_COOLDOWN                        _UxGT("カネツテイシ")                  
#define MSG_SWITCH_PS_ON                    _UxGT("デンゲン オン")                 
#define MSG_SWITCH_PS_OFF                   _UxGT("デンゲン オフ")                 
#define MSG_EXTRUDE                         _UxGT("オシダシ")                     
#define MSG_RETRACT                         _UxGT("ヒキコミセッテイ")                
#define MSG_MOVE_AXIS                       _UxGT("ジクイドウ")                    
#define MSG_BED_LEVELING                    _UxGT("ベッドレベリング")                
#define MSG_LEVEL_BED                       _UxGT("ベッドレベリング")                
#define MSG_MOVING                          _UxGT("イドウチュウ")                   
#define MSG_FREE_XY                         _UxGT("XYジク カイホウ")                
#define MSG_MOVE_X                          _UxGT("Xジク イドウ")                  
#define MSG_MOVE_Y                          _UxGT("Yジク イドウ")                  
#define MSG_MOVE_Z                          _UxGT("Zジク イドウ")                  
#define MSG_MOVE_E                          _UxGT("エクストルーダー")                
#define MSG_MOVE_01MM                       _UxGT("0.1mm イドウ")                 
#define MSG_MOVE_1MM                        _UxGT("  1mm イドウ")                 
#define MSG_MOVE_10MM                       _UxGT(" 10mm イドウ")                 
#define MSG_SPEED                           _UxGT("ソクド")                       
#define MSG_BED_Z                           _UxGT("Zオフセット")                   
#define MSG_NOZZLE                          _UxGT("ノズル")                       
#define MSG_BED                             _UxGT("ベッド")                       
#define MSG_FAN_SPEED                       _UxGT("ファンソクド")                    
#define MSG_FLOW                            _UxGT("トシュツリョウ")                   
#define MSG_CONTROL                         _UxGT("セイギョ")                      
#define MSG_MIN                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" サイテイ") 
#define MSG_MAX                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" サイコウ") 
#define MSG_FACTOR                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" ファクター") 
#define MSG_AUTOTEMP                        _UxGT("ジドウオンドセイギョ")               
#define MSG_ON                              _UxGT("オン ")                         
#define MSG_OFF                             _UxGT("オフ ")                         
#define MSG_PID_P                           _UxGT("PID-P")
#define MSG_PID_I                           _UxGT("PID-I")
#define MSG_PID_D                           _UxGT("PID-D")
#define MSG_PID_C                           _UxGT("PID-C")
#define MSG_SELECT                          _UxGT("センタク")                     
#define MSG_ACC                             _UxGT("カソクド mm/s2")               
#define MSG_JERK                            _UxGT("ヤクド mm/s")                  
#define MSG_VX_JERK                         _UxGT("Xジク ヤクド mm/s")             
#define MSG_VY_JERK                         _UxGT("Yジク ヤクド mm/s")             
#define MSG_VZ_JERK                         _UxGT("Zジク ヤクド mm/s")             
#define MSG_VE_JERK                         _UxGT("エクストルーダー ヤクド")          
#define MSG_VMAX                            _UxGT("サイダイオクリソクド ")            
#define MSG_VMIN                            _UxGT("サイショウオクリソクド")           
#define MSG_VTRAV_MIN                       _UxGT("サイショウイドウソクド")           
#define MSG_ACCELERATION                    MSG_ACC
#define MSG_AMAX                            _UxGT("サイダイカソクド ")              
#define MSG_A_RETRACT                       _UxGT("ヒキコミカソクド")               
#define MSG_A_TRAVEL                        _UxGT("イドウカソクド")                
#define MSG_TEMPERATURE                     _UxGT("オンド")                      
#define MSG_MOTION                          _UxGT("ウゴキセッテイ")                
#define MSG_FILAMENT                        _UxGT("フィラメント")                   
#define MSG_VOLUMETRIC_ENABLED              _UxGT("E in mm3")
#define MSG_FILAMENT_DIAM                   _UxGT("フィラメントチョッケイ")            
#define MSG_CONTRAST                        _UxGT("LCDコントラスト")               
#define MSG_STORE_EEPROM                    _UxGT("メモリヘカクノウ")               
#define MSG_LOAD_EEPROM                     _UxGT("メモリカラヨミコミ")               
#define MSG_RESTORE_FAILSAFE                _UxGT("セッテイリセット")               
#define MSG_REFRESH                         _UxGT("リフレッシュ")                  
#define MSG_WATCH                           _UxGT("ジョウホウガメン")               
#define MSG_PREPARE                         _UxGT("ジュンビセッテイ")               
#define MSG_TUNE                            _UxGT("チョウセイ")                    
#define MSG_PAUSE_PRINT                     _UxGT("イチジテイシ")                  
#define MSG_RESUME_PRINT                    _UxGT("プリントサイカイ")                
#define MSG_STOP_PRINT                      _UxGT("プリントテイシ")                 
#define MSG_CARD_MENU                       _UxGT("SDカードカラプリント")            
#define MSG_NO_CARD                         _UxGT("SDカードガアリマセン")            
#define MSG_DWELL                           _UxGT("キュウシ")                     
#define MSG_USERWAIT                        _UxGT("シバラクオマチクダサイ")           
#define MSG_RESUMING                        _UxGT("プリントサイカイ")                
#define MSG_PRINT_ABORTED                   _UxGT("プリントガチュウシサレマシタ")       
#define MSG_NO_MOVE                         _UxGT("ウゴキマセン")                  
#define MSG_KILLED                          _UxGT("ヒジョウテイシ")                  
#define MSG_STOPPED                         _UxGT("テイシシマシタ")                  
#define MSG_CONTROL_RETRACT                 _UxGT("ヒキコミリョウ mm")                
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("ヒキコミリョウS mm")               
#define MSG_CONTROL_RETRACTF                _UxGT("ヒキコミソクド mm/s")             
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("ノズルタイヒ mm")                
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("ホショウリョウ mm")               
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("ホショウリョウS mm")              
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("ホショウソクド mm/s")            
#define MSG_AUTORETRACT                     _UxGT("ジドウヒキコミ")                 
#define MSG_FILAMENTCHANGE                  _UxGT("フィラメントコウカン")              
#define MSG_INIT_SDCARD                     _UxGT("SDカードサイヨミコミ")             
#define MSG_CNG_SDCARD                      _UxGT("SDカードコウカン")               
#define MSG_ZPROBE_OUT                      _UxGT("Zプローブ ベッドガイ")            
#define MSG_BLTOUCH_SELFTEST                _UxGT("BLTouch ジコシンダン")          
#define MSG_BLTOUCH_RESET                   _UxGT("BLTouch リセット")             
#define MSG_HOME                            _UxGT("サキニ")                      
#define MSG_FIRST                           _UxGT("ヲフッキサセテクダサイ")           
#define MSG_ZPROBE_ZOFFSET                  _UxGT("Zオフセット")                   
#define MSG_BABYSTEP_X                      _UxGT("Xジク ビドウ")                  
#define MSG_BABYSTEP_Y                      _UxGT("Yジク ビドウ")                  
#define MSG_BABYSTEP_Z                      _UxGT("Zジク ビドウ")                  
#define MSG_ENDSTOP_ABORT                   _UxGT("イドウゲンカイケンチキノウ")         
#define MSG_HEATING_FAILED_LCD              _UxGT("カネツシッパイ")                 
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("エラー:ジョウチョウサーミスターキノウ")  
#define MSG_THERMAL_RUNAWAY                 _UxGT("ネツボウソウ")                   
#define MSG_ERR_MAXTEMP                     _UxGT("エラー:サイコウオンチョウカ")         
#define MSG_ERR_MINTEMP                     _UxGT("エラー:サイテイオンミマン")          
#define MSG_ERR_MAXTEMP_BED                 _UxGT("エラー:ベッド サイコウオンチョウカ")    
#define MSG_ERR_MINTEMP_BED                 _UxGT("エラー:ベッド サイテイオンミマン")     
#define MSG_ERR_Z_HOMING                    MSG_HOME _UxGT(" ") MSG_X MSG_Y _UxGT(" ") MSG_FIRST 
#define MSG_HALTED                          _UxGT("プリンターハテイシシマシタ")         
#define MSG_PLEASE_RESET                    _UxGT("リセットシテクダサイ")              
#define MSG_SHORT_DAY                       _UxGT("d")                          
#define MSG_SHORT_HOUR                      _UxGT("h")                          
#define MSG_SHORT_MINUTE                    _UxGT("m")                          
#define MSG_HEATING                         _UxGT("カネツチュウ")                   
#define MSG_HEATING_COMPLETE                _UxGT("カネツカンリョウ")                 
#define MSG_BED_HEATING                     _UxGT("ベッド カネツチュウ")              
#define MSG_BED_DONE                        _UxGT("ベッド カネツカンリョウ")            
#define MSG_DELTA_CALIBRATE                 _UxGT("デルタ コウセイ")                
#define MSG_DELTA_CALIBRATE_X               _UxGT("Xジク コウセイ")                 
#define MSG_DELTA_CALIBRATE_Y               _UxGT("Yジク コウセイ")                 
#define MSG_DELTA_CALIBRATE_Z               _UxGT("Zジク コウセイ")                 
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("チュウシン コウセイ")              
#define MSG_INFO_MENU                       _UxGT("コノプリンターニツイテ")             
#define MSG_INFO_PRINTER_MENU               _UxGT("プリンタージョウホウ")              
#define MSG_INFO_STATS_MENU                 _UxGT("プリントジョウキョウ")              
#define MSG_INFO_BOARD_MENU                 _UxGT("セイギョケイジョウホウ")            
#define MSG_INFO_THERMISTOR_MENU            _UxGT("サーミスター")                   
#define MSG_INFO_EXTRUDERS                  _UxGT("エクストルーダースウ")             
#define MSG_INFO_BAUDRATE                   _UxGT("ボーレート")                    
#define MSG_INFO_PROTOCOL                   _UxGT("プロトコル")                    
#define MSG_CASE_LIGHT                      _UxGT("キョウタイナイショウメイ")       
#define MSG_INFO_PRINT_COUNT                _UxGT("プリントスウ ")                  
#define MSG_INFO_COMPLETED_PRINTS           _UxGT("カンリョウスウ")                  
#define MSG_INFO_PRINT_TIME                 _UxGT("プリントジカンルイケイ")            
#define MSG_INFO_PRINT_LONGEST              _UxGT("サイチョウプリントジカン")           
#define MSG_INFO_PRINT_FILAMENT             _UxGT("フィラメントシヨウリョウルイケイ")       
#define MSG_INFO_MIN_TEMP                   _UxGT("セッテイサイテイオン")              
#define MSG_INFO_MAX_TEMP                   _UxGT("セッテイサイコウオン")              
#define MSG_INFO_PSU                        _UxGT("デンゲンシュベツ")                
#define MSG_DRIVE_STRENGTH                  _UxGT("モータークドウリョク")              
#define MSG_DAC_PERCENT                     _UxGT("DACシュツリョク %")               
#define MSG_DAC_EEPROM_WRITE                MSG_STORE_EPROM                     
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("PRINT PAUSED")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("RESUME OPTIONS:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("サラニオシダス")                 
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("プリントサイカイ")                
#define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("コウカンヲカイシシマス")            
#define MSG_FILAMENT_CHANGE_INIT_2          _UxGT("シバラクオマチクダサイ")            
#define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("フィラメントヌキダシチュウ")          
#define MSG_FILAMENT_CHANGE_UNLOAD_2        _UxGT("シバラクオマチクダサイ")            
#define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("フィラメントヲソウニュウシ,")         
#define MSG_FILAMENT_CHANGE_INSERT_2        _UxGT("クリックスルトゾッコウシマス")         
#define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("フィラメントソウテンチュウ")          
#define MSG_FILAMENT_CHANGE_LOAD_2          _UxGT("シバラクオマチクダサイ")            
#define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("フィラメントオシダシチュウ")          
#define MSG_FILAMENT_CHANGE_EXTRUDE_2       _UxGT("シバラクオマチクダサイ")            
#define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("プリントヲサイカイシマス")           
#define MSG_FILAMENT_CHANGE_RESUME_2        _UxGT("シバラクオマチクダサイ")            
#endif 
