#ifndef LANGUAGE_ZH_TW_H
#define LANGUAGE_ZH_TW_H
#define WELCOME_MSG                         MACHINE_NAME _UxGT("已就緒.")  
#define MSG_SD_INSERTED                     _UxGT("記憶卡已插入")  
#define MSG_SD_REMOVED                      _UxGT("記憶卡被拔出")  
#define MSG_LCD_ENDSTOPS                    _UxGT("擋塊")  
#define MSG_MAIN                            _UxGT("主選單")  
#define MSG_AUTOSTART                       _UxGT("自動開始")  
#define MSG_DISABLE_STEPPERS                _UxGT("關閉步進驅動")  
#define MSG_AUTO_HOME                       _UxGT("自動回原點")  
#define MSG_AUTO_HOME_X                     _UxGT("回X原位")  
#define MSG_AUTO_HOME_Y                     _UxGT("回Y原位")  
#define MSG_AUTO_HOME_Z                     _UxGT("回Z原位")  
#define MSG_LEVEL_BED_HOMING                _UxGT("平台調平XYZ歸原位")  
#define MSG_LEVEL_BED_WAITING               _UxGT("單擊開始熱床調平")  
#define MSG_LEVEL_BED_NEXT_POINT            _UxGT("下個熱床調平點")  
#define MSG_LEVEL_BED_DONE                  _UxGT("完成熱床調平")  
#define MSG_SET_HOME_OFFSETS                _UxGT("設置原點偏移")  
#define MSG_HOME_OFFSETS_APPLIED            _UxGT("偏移已啟用")  
#define MSG_SET_ORIGIN                      _UxGT("設置原點")  
#define MSG_PREHEAT_1                       _UxGT("預熱PLA")  
#define MSG_PREHEAT_1_N                     MSG_PREHEAT_1 _UxGT(" ")  
#define MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 _UxGT(" 全部")  
#define MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 _UxGT(" 熱床")  
#define MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 _UxGT(" 設置")  
#define MSG_PREHEAT_2                       _UxGT("預熱ABS")  
#define MSG_PREHEAT_2_N                     MSG_PREHEAT_2 _UxGT(" ")  
#define MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 _UxGT(" 全部")  
#define MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 _UxGT(" 熱床")  
#define MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 _UxGT(" 設置")  
#define MSG_COOLDOWN                        _UxGT("降溫")  
#define MSG_SWITCH_PS_ON                    _UxGT("電源打開")  
#define MSG_SWITCH_PS_OFF                   _UxGT("電源關閉")  
#define MSG_EXTRUDE                         _UxGT("擠出")  
#define MSG_RETRACT                         _UxGT("回抽")  
#define MSG_MOVE_AXIS                       _UxGT("移動軸")  
#define MSG_BED_LEVELING                    _UxGT("調平熱床")  
#define MSG_LEVEL_BED                       _UxGT("調平熱床")  
#define MSG_MOVE_X                          _UxGT("移動X")  
#define MSG_MOVE_Y                          _UxGT("移動Y")  
#define MSG_MOVE_Z                          _UxGT("移動Z")  
#define MSG_MOVE_E                          _UxGT("擠出機")  
#define MSG_MOVE_01MM                       _UxGT("移動 0.1 mm")  
#define MSG_MOVE_1MM                        _UxGT("移動 1 mm")  
#define MSG_MOVE_10MM                       _UxGT("移動 10 mm")  
#define MSG_SPEED                           _UxGT("速率")  
#define MSG_BED_Z                           _UxGT("熱床Z")  
#define MSG_NOZZLE                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 噴嘴")  
#define MSG_BED                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 熱床")  
#define MSG_FAN_SPEED                       _UxGT("風扇速率")  
#define MSG_FLOW                            _UxGT("擠出速率")  
#define MSG_CONTROL                         _UxGT("控制")  
#define MSG_MIN                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 最小") 
#define MSG_MAX                             _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 最大")  
#define MSG_FACTOR                          _UxGT(" ") LCD_STR_THERMOMETER _UxGT(" 系數")  
#define MSG_AUTOTEMP                        _UxGT("自動控溫")  
#define MSG_ON                              _UxGT("開 ")  
#define MSG_OFF                             _UxGT("關 ")  
#define MSG_PID_P                           _UxGT("PID-P")  
#define MSG_PID_I                           _UxGT("PID-I")  
#define MSG_PID_D                           _UxGT("PID-D")  
#define MSG_PID_C                           _UxGT("PID-C")  
#define MSG_SELECT                          _UxGT("選擇")  
#define MSG_ACC                             _UxGT("加速度")  
#define MSG_JERK                            _UxGT("抖動速率")  
#define MSG_VX_JERK                         _UxGT("X軸抖動速率")  
#define MSG_VY_JERK                         _UxGT("Y軸抖動速率")  
#define MSG_VZ_JERK                         _UxGT("Z軸抖動速率")  
#define MSG_VE_JERK                         _UxGT("擠出機抖動速率")  
#define MSG_VMAX                            _UxGT("最大進料速率")  
#define MSG_VMIN                            _UxGT("最小進料速率")  
#define MSG_VTRAV_MIN                       _UxGT("最小移動速率")  
#define MSG_AMAX                            _UxGT("最大列印加速度")  
#define MSG_A_RETRACT                       _UxGT("收進加速度")  
#define MSG_A_TRAVEL                        _UxGT("非列印移動加速度")  
#define MSG_STEPS_PER_MM                    _UxGT("軸步數/mm")  
#define MSG_XSTEPS                          _UxGT("X軸步數/mm")  
#define MSG_YSTEPS                          _UxGT("Y軸步數/mm")  
#define MSG_ZSTEPS                          _UxGT("Z軸步數/mm")  
#define MSG_ESTEPS                          _UxGT("擠出機步數/mm")  
#define MSG_TEMPERATURE                     _UxGT("溫度")  
#define MSG_MOTION                          _UxGT("運動")  
#define MSG_FILAMENT                        _UxGT("絲料測容")  
#define MSG_VOLUMETRIC_ENABLED              _UxGT("測容積mm³")  
#define MSG_FILAMENT_DIAM                   _UxGT("絲料直徑")  
#define MSG_CONTRAST                        _UxGT("LCD對比度")  
#define MSG_STORE_EEPROM                    _UxGT("保存設置")  
#define MSG_LOAD_EEPROM                     _UxGT("裝載設置")  
#define MSG_RESTORE_FAILSAFE                _UxGT("恢複安全值")  
#define MSG_REFRESH                         _UxGT("刷新")  
#define MSG_WATCH                           _UxGT("資訊界面")  
#define MSG_PREPARE                         _UxGT("準備")  
#define MSG_TUNE                            _UxGT("調整")  
#define MSG_PAUSE_PRINT                     _UxGT("暫停列印")  
#define MSG_RESUME_PRINT                    _UxGT("恢複列印")  
#define MSG_STOP_PRINT                      _UxGT("停止列印")  
#define MSG_CARD_MENU                       _UxGT("從記憶卡上列印")  
#define MSG_NO_CARD                         _UxGT("無記憶卡")  
#define MSG_DWELL                           _UxGT("休眠 ...")  
#define MSG_USERWAIT                        _UxGT("等待用戶 ...")  
#define MSG_RESUMING                        _UxGT("恢複列印中")  
#define MSG_PRINT_ABORTED                   _UxGT("列印已取消")  
#define MSG_NO_MOVE                         _UxGT("無移動")  
#define MSG_KILLED                          _UxGT("已殺掉")  
#define MSG_STOPPED                         _UxGT("已停止")  
#define MSG_CONTROL_RETRACT                 _UxGT("回抽長度mm")  
#define MSG_CONTROL_RETRACT_SWAP            _UxGT("換手回抽長度mm")  
#define MSG_CONTROL_RETRACTF                _UxGT("回抽速率mm/s")  
#define MSG_CONTROL_RETRACT_ZLIFT           _UxGT("Hop mm")  
#define MSG_CONTROL_RETRACT_RECOVER         _UxGT("回抽恢複長度mm")  
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    _UxGT("換手回抽恢複長度mm")  
#define MSG_CONTROL_RETRACT_RECOVERF        _UxGT("回抽恢複後進料速率mm/s")  
#define MSG_AUTORETRACT                     _UxGT("自動抽回")  
#define MSG_FILAMENTCHANGE                  _UxGT("更換絲料")  
#define MSG_INIT_SDCARD                     _UxGT("初始化記憶卡")  
#define MSG_CNG_SDCARD                      _UxGT("更換記憶卡")  
#define MSG_ZPROBE_OUT                      _UxGT("Z探針在熱床之外")  
#define MSG_HOME                            _UxGT("歸位")  
#define MSG_FIRST                           _UxGT("先")  
#define MSG_ZPROBE_ZOFFSET                  _UxGT("Z偏移")  
#define MSG_BABYSTEP_X                      _UxGT("微量調整X軸")  
#define MSG_BABYSTEP_Y                      _UxGT("微量調整Y軸")  
#define MSG_BABYSTEP_Z                      _UxGT("微量調整Z軸")  
#define MSG_ENDSTOP_ABORT                   _UxGT("擋塊終止")  
#define MSG_HEATING_FAILED_LCD              _UxGT("加熱失敗")  
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("錯誤：REDUNDANT TEMP")  
#define MSG_THERMAL_RUNAWAY                 _UxGT("溫控失控")  
#define MSG_ERR_MAXTEMP                     _UxGT("錯誤：最高溫度")  
#define MSG_ERR_MINTEMP                     _UxGT("錯誤：最低溫度")  
#define MSG_ERR_MAXTEMP_BED                 _UxGT("錯誤：最高熱床溫度")  
#define MSG_ERR_MINTEMP_BED                 _UxGT("錯誤：最低熱床溫度")  
#define MSG_HALTED                          _UxGT("印表機停機")  
#define MSG_PLEASE_RESET                    _UxGT("請重置")  
#define MSG_SHORT_DAY                       _UxGT("天")  
#define MSG_SHORT_HOUR                      _UxGT("時")  
#define MSG_SHORT_MINUTE                    _UxGT("分")  
#define MSG_HEATING                         _UxGT("加熱中 ...")  
#define MSG_HEATING_COMPLETE                _UxGT("完成加熱")  
#define MSG_BED_HEATING                     _UxGT("加熱熱床中")  
#define MSG_BED_DONE                        _UxGT("完成加熱熱床")  
#define MSG_DELTA_CALIBRATE                 _UxGT("⊿校準")  
#define MSG_DELTA_CALIBRATE_X               _UxGT("校準X")  
#define MSG_DELTA_CALIBRATE_Y               _UxGT("校準Y")  
#define MSG_DELTA_CALIBRATE_Z               _UxGT("校準Z")  
#define MSG_DELTA_CALIBRATE_CENTER          _UxGT("校準中心")  
#define MSG_INFO_MENU                       _UxGT("關於印表機")  
#define MSG_INFO_PRINTER_MENU               _UxGT("印表機信息")  
#define MSG_INFO_STATS_MENU                 _UxGT("印表機統計")  
#define MSG_INFO_BOARD_MENU                 _UxGT("主板信息")  
#define MSG_INFO_THERMISTOR_MENU            _UxGT("溫度計")  
#define MSG_INFO_EXTRUDERS                  _UxGT("擠出機")  
#define MSG_INFO_BAUDRATE                   _UxGT("波特率")  
#define MSG_INFO_PROTOCOL                   _UxGT("協議")  
#if LCD_WIDTH > 19
#define MSG_INFO_PRINT_COUNT              _UxGT("列印計數")  
#define MSG_INFO_COMPLETED_PRINTS         _UxGT("完成了")  
#define MSG_INFO_PRINT_TIME               _UxGT("總列印時間")  
#define MSG_INFO_PRINT_LONGEST            _UxGT("最長工作時間")  
#define MSG_INFO_PRINT_FILAMENT           _UxGT("總計擠出")  
#else
#define MSG_INFO_PRINT_COUNT              _UxGT("列印數")  
#define MSG_INFO_COMPLETED_PRINTS         _UxGT("完成")  
#define MSG_INFO_PRINT_TIME               _UxGT("總共")  
#define MSG_INFO_PRINT_LONGEST            _UxGT("最長")  
#define MSG_INFO_PRINT_FILAMENT           _UxGT("已擠出")  
#endif
#define MSG_INFO_MIN_TEMP                   _UxGT("最低溫度")  
#define MSG_INFO_MAX_TEMP                   _UxGT("最高溫度")  
#define MSG_INFO_PSU                        _UxGT("電源供應")  
#define MSG_FILAMENT_CHANGE_HEADER          _UxGT("PRINT PAUSED")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("RESUME OPTIONS:")
#define MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  _UxGT("擠出更多")  
#define MSG_FILAMENT_CHANGE_OPTION_RESUME   _UxGT("恢複列印")  
#if LCD_HEIGHT >= 4
#define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("等待開始")  
#define MSG_FILAMENT_CHANGE_INIT_2          _UxGT("絲料")  
#define MSG_FILAMENT_CHANGE_INIT_3          _UxGT("變更")  
#define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("等待")  
#define MSG_FILAMENT_CHANGE_UNLOAD_2        _UxGT("卸下絲料")  
#define MSG_FILAMENT_CHANGE_UNLOAD_3        _UxGT("")  
#define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("插入絲料")  
#define MSG_FILAMENT_CHANGE_INSERT_2        _UxGT("並按鍵")  
#define MSG_FILAMENT_CHANGE_INSERT_3        _UxGT("來繼續 ...")  
#define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("等待")  
#define MSG_FILAMENT_CHANGE_LOAD_2          _UxGT("進料")  
#define MSG_FILAMENT_CHANGE_LOAD_3          _UxGT("")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("等待")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_2       _UxGT("絲料擠出")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_3       _UxGT("")  
#define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("等待列印")  
#define MSG_FILAMENT_CHANGE_RESUME_2        _UxGT("恢複")  
#define MSG_FILAMENT_CHANGE_RESUME_3        _UxGT("")  
#else 
#define MSG_FILAMENT_CHANGE_INIT_1          _UxGT("請等待 ...")  
#define MSG_FILAMENT_CHANGE_UNLOAD_1        _UxGT("退出中 ...")  
#define MSG_FILAMENT_CHANGE_INSERT_1        _UxGT("插入並單擊")  
#define MSG_FILAMENT_CHANGE_LOAD_1          _UxGT("裝載中 ...")  
#define MSG_FILAMENT_CHANGE_EXTRUDE_1       _UxGT("擠出中 ...")  
#define MSG_FILAMENT_CHANGE_RESUME_1        _UxGT("恢複中 ...")  
#endif 
#endif 
