#ifndef __PINSDEBUG_PLUS_70_H__
#define __PINSDEBUG_PLUS_70_H__
#undef NUM_DIGITAL_PINS
#if MOTHERBOARD == BOARD_BQ_ZUM_MEGA_3D
  #define NUM_DIGITAL_PINS            85
#elif MOTHERBOARD == BOARD_MIGHTYBOARD_REVE
  #define NUM_DIGITAL_PINS            80
#elif MOTHERBOARD == BOARD_MINIRAMBO
  #define NUM_DIGITAL_PINS            85
#elif MOTHERBOARD == BOARD_SCOOVO_X9H
  #define NUM_DIGITAL_PINS            85
#endif
#define PA 1
#define PB 2
#define PC 3
#define PD 4
#define PE 5
#define PF 6
#define PG 7
#define PH 8
#define PJ 10
#define PK 11
#define PL 12
const uint8_t PROGMEM digital_pin_to_port_PGM_plus_70[] = {
  PE  , 
  PE  , 
  PE  , 
  PE  , 
  PG  , 
  PE  , 
  PH  , 
  PH  , 
  PH  , 
  PH  , 
  PB  , 
  PB  , 
  PB  , 
  PB  , 
  PJ  , 
  PJ  , 
  PH  , 
  PH  , 
  PD  , 
  PD  , 
  PD  , 
  PD  , 
  PA  , 
  PA  , 
  PA  , 
  PA  , 
  PA  , 
  PA  , 
  PA  , 
  PA  , 
  PC  , 
  PC  , 
  PC  , 
  PC  , 
  PC  , 
  PC  , 
  PC  , 
  PC  , 
  PD  , 
  PG  , 
  PG  , 
  PG  , 
  PL  , 
  PL  , 
  PL  , 
  PL  , 
  PL  , 
  PL  , 
  PL  , 
  PL  , 
  PB  , 
  PB  , 
  PB  , 
  PB  , 
  PF  , 
  PF  , 
  PF  , 
  PF  , 
  PF  , 
  PF  , 
  PF  , 
  PF  , 
  PK  , 
  PK  , 
  PK  , 
  PK  , 
  PK  , 
  PK  , 
  PK  , 
  PK  , 
  PG  , 
  PG  , 
  PJ  , 
  PJ  , 
  PJ  , 
  PJ  , 
  PJ  , 
  PJ  , 
  PE  , 
  PE  , 
  PE  , 
  PD  , 
  PD  , 
  PD  , 
  PH  , 
  PH  , 
};
#define digitalPinToPort_plus_70(P) ( pgm_read_byte( digital_pin_to_port_PGM_plus_70 + (P) ) )
const uint8_t PROGMEM digital_pin_to_bit_mask_PGM_plus_70[] = {
  _BV( 0 )  , 
  _BV( 1 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 5 )  , 
  _BV( 3 )  , 
  _BV( 3 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 6 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 6 )  , 
  _BV( 7 )  , 
  _BV( 1 )  , 
  _BV( 0 )  , 
  _BV( 1 )  , 
  _BV( 0 )  , 
  _BV( 3 )  , 
  _BV( 2 )  , 
  _BV( 1 )  , 
  _BV( 0 )  , 
  _BV( 0 )  , 
  _BV( 1 )  , 
  _BV( 2 )  , 
  _BV( 3 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 6 )  , 
  _BV( 7 )  , 
  _BV( 7 )  , 
  _BV( 6 )  , 
  _BV( 5 )  , 
  _BV( 4 )  , 
  _BV( 3 )  , 
  _BV( 2 )  , 
  _BV( 1 )  , 
  _BV( 0 )  , 
  _BV( 7 )  , 
  _BV( 2 )  , 
  _BV( 1 )  , 
  _BV( 0 )  , 
  _BV( 7 )  , 
  _BV( 6 )  , 
  _BV( 5 )  , 
  _BV( 4 )  , 
  _BV( 3 )  , 
  _BV( 2 )  , 
  _BV( 1 )  , 
  _BV( 0 )  , 
  _BV( 3 )  , 
  _BV( 2 )  , 
  _BV( 1 )  , 
  _BV( 0 )  , 
  _BV( 0 )  , 
  _BV( 1 )  , 
  _BV( 2 )  , 
  _BV( 3 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 6 )  , 
  _BV( 7 )  , 
  _BV( 0 )  , 
  _BV( 1 )  , 
  _BV( 2 )  , 
  _BV( 3 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 6 )  , 
  _BV( 7 )  , 
  _BV( 4 )  , 
  _BV( 3 )  , 
  _BV( 2 )  , 
  _BV( 3 )  , 
  _BV( 7 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 6 )  , 
  _BV( 2 )  , 
  _BV( 6 )  , 
  _BV( 7 )  , 
  _BV( 4 )  , 
  _BV( 5 )  , 
  _BV( 6 )  , 
  _BV( 2 )  , 
  _BV( 7 )  , 
};
#define digitalPinToBitMask_plus_70(P) ( pgm_read_byte( digital_pin_to_bit_mask_PGM_plus_70 + (P) ) )
const uint8_t PROGMEM digital_pin_to_timer_PGM_plus_70[] = {
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  TIMER3B , 
  TIMER3C , 
  TIMER0B , 
  TIMER3A , 
  TIMER4A , 
  TIMER4B , 
  TIMER4C , 
  TIMER2B , 
  TIMER2A , 
  TIMER1A , 
  TIMER1B , 
  TIMER0A , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  TIMER5C , 
  TIMER5B , 
  TIMER5A , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
  NOT_ON_TIMER  , 
};
#define digitalPinToTimer_plus_70(P) ( pgm_read_byte( digital_pin_to_timer_PGM_plus_70 + (P) ) )
#endif 
