#ifndef DUMMY_THERMISTOR_999_VALUE
  #define DUMMY_THERMISTOR_999_VALUE 25
#endif
const short temptable_999[][2] PROGMEM = {
  {    1 * OVERSAMPLENR, DUMMY_THERMISTOR_999_VALUE },
  { 1023 * OVERSAMPLENR, DUMMY_THERMISTOR_999_VALUE }
};
