#ifndef DUMMY_THERMISTOR_998_VALUE
  #define DUMMY_THERMISTOR_998_VALUE 25
#endif
const short temptable_998[][2] PROGMEM = {
  {    1 * OVERSAMPLENR, DUMMY_THERMISTOR_998_VALUE },
  { 1023 * OVERSAMPLENR, DUMMY_THERMISTOR_998_VALUE }
};
